### ISSUE TITLE
Configuring Severity.Debug or higher leads to System.StackOverflowException

### ISSUE THREAD

**Issue by fmjensen** [Somfic/EliteAPI#28] opened 2019-12-23 08:40 UTC
This is the output in console when using 
`EliteAPI.Logger.UseConsole(Severity.Debug);`
as configuration:

```Info    ─  Starting EliteAPI.
Debug   ─  EliteAPI by CMDR Somfic (discord.gg/jwpFUPZ) (github.com/EliteAPI/EliteAPI).
Debug   ─  EliteAPI v2.2.23.879.
Debug   ─  Checking for updates from GitHub.
Debug   ─  Latest version: 2.2.23.879 (curr. 2.2.23.879).
Debug   ─  EliteAPI is up-to-date with the latest version.
Info    ─  Journal directory set to 'C:\Users\<USERNAME>\Saved Games\Frontier Developments\Elite Dangerous'.
Debug   ─  Searching for 'Journal.*.log' files.
Debug   ─  Found 'Journal.191222135652.01.log'.
Debug   ─  Found 'Status.json'.
Debug   ─  Found 'Cargo.json'.
Debug   ─  Found 'Shipyard.json'.
Debug   ─  Found 'Outfitting.json'.
Debug   ─  Found 'Market.json'.
Debug   ─  Found 'ModulesInfo.json'.
Info    ─  Found Journal and Status files.
Warning ─  Elite: Dangerous is not in-game.
Debug   ─  Catching up with past events from this session.
Debug   ─  Processing event 'Fileheader'.
Debug
Process is terminated due to StackOverflowException.

**Comment by fmjensen** [comment] 2019-12-23 08:50
This is the details from VS debugger:

    System.StackOverflowException
      HResult=0x800703E9
      Source=<Cannot evaluate the exception source>
      StackTrace:
    <Cannot evaluate the exception stack trace>

**Comment by Somfic** [comment] 2019-12-23 10:33
Hi fmjensen,

Could you send me Journal.191222135652.01.log for further inspection?

**Comment by fmjensen** [comment] 2019-12-23 10:51
Sure - but i don't think it is related to the content of the journals - i discovered it a couple of days ago but didn't report it because i wanted to be sure my code wasn't the cause.
[Journal.191222135652.01.log](https://github.com/EliteAPI/EliteAPI/files/3994644/Journal.191222135652.01.log)

**Comment by Somfic** [comment] 2019-12-23 12:09
The problem seems to be caused by my logging engine. The temporary fix is to call the `.UseFormat(false)` method in `EliteAPI.Logger`

**Comment by Somfic** [comment] 2019-12-31 21:40
This issue should be fixed with the new logging framework.

**Closed as completed by Somfic** 2019-12-31 21:40 UTC
